name: ANNA grows old

on:
  push:
    branches:
      - main

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: ANNA grows old
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN_FOR_CHECKOUT_SUBMODULE }}
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.5.1
      - name: ready
        run: poetry install --with ci
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: fly deploy --config .meta/deploy/fly.toml --dockerfile .meta/deploy/Dockerfile --remote-only # make deploy_remote # fly not found 발생해서 그냥 script 를 Makefile 로부터 복붙함
