name: ANNA grows old

on:
  push:
    branches:
      - main

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: ANNA grows old
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN_FOR_CHECKOUT_SUBMODULE }}
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.5.1
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: make deploy_remote
